<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Birthday</name>
   <tag></tag>
   <elementGuidId>70987c88-6320-4290-a23c-a08d38f95b2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#birthday</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='birthday']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9fd74c79-719f-4c87-97ca-4d5647deac16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>66535008-8f66-4bd3-ab11-98626bad4892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date</value>
      <webElementGuid>25178908-5b31-4e73-8ae8-2573ae4dea06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthday</value>
      <webElementGuid>c4fb50b7-997f-49bf-8570-c279bcf9e240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birthday</value>
      <webElementGuid>8b77ceba-fcbb-44fa-9a22-606c5feccf4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ngày / tháng / năm</value>
      <webElementGuid>63ba838d-a396-4f07-9364-c989163fb390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8bca388f-c138-4638-b373-0ea92c4a6410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-notempty</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c34240a3-f864-431f-ab15-8562174d6f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-notempty-message</name>
      <type>Main</type>
      <value>Vui lòng nhập ngày sinh</value>
      <webElementGuid>4f0c504b-1f83-435e-b287-51489cf3c186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-date</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a64e7221-76e5-4612-9325-6d03e5e14d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-date-message</name>
      <type>Main</type>
      <value>Ngày sinh không hợp lệ</value>
      <webElementGuid>8b01eb47-673a-4942-a16c-027656de5d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-date-separator</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>b2772684-878d-47b0-ada9-53b0e0a86b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-date-format</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>9d561b5f-dbfe-480f-bfc8-6de533d2845d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-date-max</name>
      <type>Main</type>
      <value>05/01/2023</value>
      <webElementGuid>bcf88f65-347d-40b2-be15-10fe75cc7982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-field</name>
      <type>Main</type>
      <value>birthday</value>
      <webElementGuid>d250094a-1f86-4bf7-b119-5a9c75f675f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;birthday&quot;)</value>
      <webElementGuid>aebc2c64-a7f4-4f52-8da1-940f58f76b47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birthday']</value>
      <webElementGuid>60d26f2e-efa6-4ad9-b82a-cb2a66109086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/div[2]/form/div/div/div/div[5]/div/input</value>
      <webElementGuid>acc6172b-2813-4c0f-a043-4f217ca05720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>fa0e4640-7692-4a66-8bb4-5ee1028bdb4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'birthday' and @name = 'birthday' and @placeholder = 'Ngày / tháng / năm']</value>
      <webElementGuid>c6f9e14d-4b7c-4bb8-a203-8e6b0e5a85af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
