<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Email</name>
   <tag></tag>
   <elementGuidId>e07299fa-c9c9-4796-b5cb-5ed894f61d61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ea6d8b5-28a4-45b2-ada0-ee592d84c0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7131fdb0-8c46-4f3b-8301-0da9fe39330a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f1dccd76-dc8e-47d7-a25e-ce8cd7aa1162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f9906879-0a00-4b40-8c51-4fdd1228e7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>49afe829-69f0-4db5-89c4-ef853ea13be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập email của bạn</value>
      <webElementGuid>a4ca9ee7-c4f3-4e8d-bc02-09af54b2f27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>942afb7d-2754-4ee6-9d0b-6c01b91893c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-notempty</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f8270de6-36e0-478f-89ff-cdf0b8c08ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-notempty-message</name>
      <type>Main</type>
      <value>Vui lòng nhập Email</value>
      <webElementGuid>15f930f5-4b21-4c07-8ff1-d537c5f77fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-stringlength</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2033d2d3-b61f-4c63-a63d-9fafd3ee00b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-stringlength-max</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>f6a4bdaa-8410-42e0-becd-6ffc3ad134d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-stringlength-message</name>
      <type>Main</type>
      <value>Email nhập tối đa 60 ký tự</value>
      <webElementGuid>34f9548d-613a-4e5e-8844-8470198ffdae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$</value>
      <webElementGuid>e87e3607-d0eb-49c7-8cd2-bd3f95958ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-regexp-message</name>
      <type>Main</type>
      <value>Email không hợp lệ</value>
      <webElementGuid>35857d3f-fddd-4f26-b791-9c9daba7709e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-field</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2cf5b7d9-77c4-4d5c-9ace-275a3229b3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email&quot;)</value>
      <webElementGuid>33454dc6-6a84-4f58-89cd-acc32625f2f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email']</value>
      <webElementGuid>90449d17-5ee2-4a6b-bf1a-5df4b70503c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/div[2]/form/div/div/div/div/div/input</value>
      <webElementGuid>bfa45698-91f5-4efc-a8b6-1cf4d632ac6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>2efc6f62-77d4-49f9-924b-265839b955ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'email' and @name = 'email' and @placeholder = 'Nhập email của bạn']</value>
      <webElementGuid>b54861ee-1805-4ed8-980d-70ef64f467e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
