<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Password</name>
   <tag></tag>
   <elementGuidId>5bf161c7-3173-4a15-9509-7fee30cb22a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-group.form-group-lg.has-feedback.has-error.fv-has-tooltip > div.input-group > #password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='password'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>590a0223-d980-4d0b-abcd-afcbb3825045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>89b825c0-7436-4348-8242-8faaad17de85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>28c7c551-ac91-4a20-a037-f89455f3894b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>19736d2e-5440-4e1b-b8d8-dc9cd250f558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8e14346d-5133-4aa8-9ceb-d90c9b3dff6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập mật khẩu</value>
      <webElementGuid>aabdcf9d-ee58-4b63-9111-01bb8568687e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>41759d72-501b-4a0f-952b-2c1684856112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-notempty</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d3ae4b0a-6ec8-4d95-a268-35602c9d4f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-notempty-message</name>
      <type>Main</type>
      <value>Vui lòng nhập mật khẩu</value>
      <webElementGuid>c6e8fed4-149d-44f7-99aa-e1152f375f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-stringlength</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3298664d-0f57-43d3-ba51-774dacb4276e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-stringlength-min</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>c1ebc3e4-1d9c-4856-8bdc-189d1a7b7cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-stringlength-max</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>485dad39-dce5-4ea2-a338-268f4298ca44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-stringlength-message</name>
      <type>Main</type>
      <value>Mật khẩu phải từ 6 đến 32 kí tự</value>
      <webElementGuid>43823d05-f66a-4051-bd91-c94d2daa868c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fv-field</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>16e056c4-8e74-4cfe-8559-67d86247f1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;content content--full&quot;]/div[@class=&quot;box box--center&quot;]/div[@class=&quot;box__body&quot;]/form[@class=&quot;form form--general form--registration fv-form fv-form-bootstrap&quot;]/div[@class=&quot;row form&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;form__inner&quot;]/div[@class=&quot;form-group form-group-lg has-feedback has-error fv-has-tooltip&quot;]/div[@class=&quot;input-group&quot;]/input[@id=&quot;password&quot;]</value>
      <webElementGuid>fc4ad2da-00a9-49a6-aacb-ce31082e9b0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='password'])[2]</value>
      <webElementGuid>4ef409eb-23f8-401f-a204-1bfac554322d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/div[2]/form/div/div/div/div[2]/div/input</value>
      <webElementGuid>6bb9d1bd-d594-4be5-9a0c-8b5ea5c978ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/input</value>
      <webElementGuid>bd8552bc-6cb7-4620-9c12-32e16642b434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'password' and @name = 'password' and @placeholder = 'Nhập mật khẩu']</value>
      <webElementGuid>d8030ead-b41e-4e82-abbc-8152bca5dc40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
