<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SignIn</name>
   <tag></tag>
   <elementGuidId>58b10e23-a606-485c-8848-446e040d9838</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-popup-header-form > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='login-popup-header-form']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>42a2fb46-45ae-427a-bb61-e03c28620256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>bbb063f5-424b-4fba-bf8e-a6bbb3f56ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>ab917375-299b-4e40-8402-17b9414464fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng nhập</value>
      <webElementGuid>29289c4e-081a-4476-b9fd-0e16683e1df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-popup-header-form&quot;)/a[1]</value>
      <webElementGuid>d919c12e-d0ef-4e97-9370-7c2fefdf8c73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='login-popup-header-form']/a</value>
      <webElementGuid>089ed778-94be-4df1-ac9b-2106b367de17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Đăng nhập')])[2]</value>
      <webElementGuid>d8d185bf-dfbf-4b20-9336-b59574dc5cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký'])[2]/following::a[1]</value>
      <webElementGuid>5a733daa-839f-4a14-90f4-4a6a463a84db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ÐĂNG NHẬP'])[1]/preceding::a[1]</value>
      <webElementGuid>1a974ded-ee02-4098-b79c-a929cf339ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vui lòng nhập Email'])[3]/preceding::a[1]</value>
      <webElementGuid>7ccc1dfc-49a5-4d25-9541-18fe9e3613c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>dc8fbdcd-798b-43c9-9d7f-7f0a53d2b32d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/div/nav/ul/li[3]/a</value>
      <webElementGuid>fa93bf92-ab27-4d83-bb25-43c233f3abda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Đăng nhập' or . = 'Đăng nhập')]</value>
      <webElementGuid>56b17345-5e56-4bd0-b47a-108927888277</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
