<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msg_Success</name>
   <tag></tag>
   <elementGuidId>9c914c4d-f580-44e3-aa68-c354759f2ccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.alert.alert-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='alertNoticeContent']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>663ffbcd-0ef0-4351-aede-c3da32b4ca99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-success</value>
      <webElementGuid>57bf6d8e-dc20-494a-a3a2-5bcec6f62648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thành công ! Đăng ký tài khoản thành công.</value>
      <webElementGuid>41650e6e-5915-4cb3-9f7f-0c4b48522132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alertNoticeContent&quot;)/div[@class=&quot;alert alert-success&quot;]</value>
      <webElementGuid>7365a8df-2a50-400b-a53d-bc5e697216f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alertNoticeContent']/div</value>
      <webElementGuid>6a76baf2-65a6-4d01-b4a2-a1e5cbc7a137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký ngay'])[1]/following::div[7]</value>
      <webElementGuid>a46ef095-7759-47f1-b6fa-343c60376c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ĐẶT HÀNG'])[1]/following::div[7]</value>
      <webElementGuid>29a550aa-0722-473c-aa97-c8d20ea0a5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chắn chắn muốn xóa ?'])[1]/preceding::div[1]</value>
      <webElementGuid>3a6fd47e-8739-4817-b9a5-ed5e53d96494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đăng ký tài khoản thành công.']/parent::*</value>
      <webElementGuid>ac975e80-56a9-4ba9-b524-3e8fc006f5c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div</value>
      <webElementGuid>103f220b-c490-4def-9b28-f0e2dc5dfa7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Thành công ! Đăng ký tài khoản thành công.' or . = 'Thành công ! Đăng ký tài khoản thành công.')]</value>
      <webElementGuid>77cdb059-18f3-48cb-b02d-3d8913e13e6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
